AWSTemplateFormatVersion: '2010-09-09'
Description: RDS MySQL for Ecommerce App (in correct VPC)

Parameters:
  DBUsername:
    Type: String
    Default: admin
  DBPassword:
    Type: String
    NoEcho: true

Resources:

  RdsSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow access to RDS MySQL
      VpcId: !ImportValue EcommerceVPCId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: RdsSecurityGroup

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for RDS
      SubnetIds:
        - !ImportValue EcommercePublicSubnet1
        - !ImportValue EcommercePublicSubnet2
      Tags:
        - Key: Name
          Value: RdsSubnetGroup

  EcommerceDB:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: mysql
      DBInstanceClass: db.t3.micro
      AllocatedStorage: 20
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      DBSubnetGroupName: !Ref DBSubnetGroup
      VPCSecurityGroups:
        - !Ref RdsSecurityGroup
      DBName: ecommerce
      PubliclyAccessible: true
      BackupRetentionPeriod: 0
      Tags:
        - Key: Name
          Value: EcommerceDB
